apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-dotnet-basic-zdyklcjh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-dotnet-basic-zdyklcjh 
  name: backend-tests-dotnet-basic-zdyklcjh
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-dotnet-basic-zdyklcjh 
